### ISSUE TITLE
Merge of plugin configs triggers IllegalArgumentException due to incorrect merging

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#103]
```
List has more than one element.
java.lang.IllegalArgumentException: List has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:608)
	at org.cqfn.save.plugin.warn.WarnPlugin.execute(WarnPlugin.kt:33)
	at org.cqfn.save.core.Save.performAnalysis(Save.kt:106)
	at org.cqfn.save.core.PluginDiscoveryTest.detect plugins(PluginDiscoveryTest.kt:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

```

Merging incorrectly adds plugins to child configs from parent and causes duplications. Instead of [WARN, GENERAL] , plugin list can contain [ WARN (parent), GENERAL(parent), WARN(child), GENERAL(child) ] plugins. 

Remove of `.also { it.merge() }` logic from save.kt solves the problem

**Comment by akuleshov7** [comment]
problem happens because of  `childConfig.add(newChildFixConfig)`
